language: cpp

addons:
 apt:
  packages:
  - clang
  - gcc
 code_climate:
  repo_token: aa4d6e58af5171733b3ba4c49e65fdd806b6af90645110abe0799462bcae908b

script:
- make CXX=clang++
- make clean
- make CXX=g++
- make clean

notifications:
 email:
  recipients:
  - dawidd0811@gmail.com
  - wojcikmikolaj1@gmail.com
  on_success: always
  on_failure: always
