language: cpp

compiler:
- clang
- gcc

before_install:
- sudo apt-get update
- sudo apt-get install clang gcc

script:
- make

notifications:
 email:
  recipients:
  - dawidd0811@gmail.com
  - wojcikmikolaj1@gmail.com
  on_success: always
  on_failure: always
