language: cpp

compiler:
- clang
- gcc

before_install:
- test -n $CC  && unset CC
- test -n $CXX && unset CXX

script:
- make

notifications:
 email:
  recipients:
  - dawidd0811@gmail.com
  - wojcikmikolaj1@gmail.com
  on_success: always
  on_failure: always
